/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1c1c",
        "on-error": "#ffffff",
        "primary": "#b90014",
        "surface-bright": "#fbf9f9",
        "surface-container-highest": "#e3e2e2",
        "surface-container-high": "#e9e8e7",
        "inverse-on-surface": "#f2f0f0",
        "on-primary-fixed-variant": "#93000d",
        "on-tertiary-fixed": "#002113",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#5d3f3c",
        "error": "#ba1a1a",
        "on-primary-container": "#fff9f8",
        "outline": "#926e6b",
        "background": "#fbf9f9",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#eefff2",
        "primary-fixed-dim": "#ffb4ac",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#303031",
        "on-secondary": "#ffffff",
        "surface-dim": "#dbdad9",
        "secondary-container": "#e5e2e1",
        "inverse-primary": "#ffb4ac",
        "surface-tint": "#c00015",
        "on-secondary-fixed": "#1c1b1b",
        "outline-variant": "#e7bdb8",
        "tertiary": "#006846",
        "primary-container": "#e31b23",
        "surface-variant": "#e3e2e2",
        "surface-container-low": "#f5f3f3",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#81f9c1",
        "on-tertiary": "#ffffff",
        "secondary": "#5f5e5e",
        "surface-container": "#efeded",
        "on-tertiary-fixed-variant": "#005236",
        "surface": "#fbf9f9",
        "primary-fixed": "#ffdad6",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#474646",
        "tertiary-fixed-dim": "#63dca6",
        "on-secondary-container": "#656464",
        "on-primary-fixed": "#410002",
        "secondary-fixed": "#e5e2e1",
        "tertiary-container": "#00845a",
        "secondary-fixed-dim": "#c8c6c5",
        // Retain brand & neon aliases if needed by admin portal
        brand: {
          50: '#fdf4ff',
          100: '#fae8ff',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
        },
        dark: {
          900: '#0b0f19',
          800: '#111827',
          700: '#1f2937',
          600: '#374151'
        }
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "2.5rem",
        "space-md": "1rem",
        "space-xl": "2rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1.25rem",
        "space-3xl": "4rem",
        "space-sm": "0.75rem",
        "space-2xs": "0.25rem",
        "container-max": "75rem",
        "space-lg": "1.5rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
        "gutter-desktop": "1.5rem"
      },
      fontFamily: {
        "data-metric": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "data-metric": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
