"""create initial schema

Revision ID: 7697af6bf914
Revises: 
Create Date: 2026-09-06 17:42:36.457757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7697af6bf914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_url', sa.String(length=255), nullable=True),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('store_address', sa.Text(), nullable=True),
    sa.Column('store_phone', sa.String(length=30), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('privacy_policy', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('max_spins_per_mobile', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('otp_verified', sa.Boolean(), nullable=False),
    sa.Column('social_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_mobile'), ['mobile'], unique=True)

    op.create_table('otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otps_mobile'), ['mobile'], unique=False)

    op.create_table('prizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='chk_prize_quantity_non_negative'),
    sa.CheckConstraint('remaining_quantity >= 0', name='chk_prize_remaining_non_negative'),
    sa.CheckConstraint('weight >= 0', name='chk_prize_weight_non_negative'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prizes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prizes_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('spins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('claim_code', sa.String(length=32), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prize_id'], ['prizes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'campaign_id', name='uq_customer_campaign_spin'),
    sa.UniqueConstraint('mobile_number', 'campaign_id', name='uq_spins_mobile_campaign')
    )
    with op.batch_alter_table('spins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spins_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spins_claim_code'), ['claim_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_spins_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spins_mobile_number'), ['mobile_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_spins_prize_id'), ['prize_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spins_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spins_status'))
        batch_op.drop_index(batch_op.f('ix_spins_prize_id'))
        batch_op.drop_index(batch_op.f('ix_spins_mobile_number'))
        batch_op.drop_index(batch_op.f('ix_spins_customer_id'))
        batch_op.drop_index(batch_op.f('ix_spins_claim_code'))
        batch_op.drop_index(batch_op.f('ix_spins_campaign_id'))

    op.drop_table('spins')
    with op.batch_alter_table('prizes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prizes_campaign_id'))

    op.drop_table('prizes')
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otps_mobile'))

    op.drop_table('otps')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_mobile'))

    op.drop_table('customers')
    op.drop_table('campaigns')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
